2022-12-16 10:38:42,706 — ERROR : Unknown error
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/get.py", line 48, in listing
    arr[i] = int(arr[i])
ValueError: invalid literal for int() with base 10: '1 2 3 4 5 6 7'
2022-12-16 10:38:46,290 — ERROR : Unknown error
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/get.py", line 48, in listing
    arr[i] = int(arr[i])
ValueError: invalid literal for int() with base 10: '1 2 3'
2022-12-16 10:39:33,239 — ERROR : You entered a non-numeric value.
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/get.py", line 16, in int
    n = int(input(hint))
ValueError: invalid literal for int() with base 10: '???'
2022-12-16 10:39:33,240 — ERROR : Please reenter a valid value.
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/get.py", line 16, in int
    n = int(input(hint))
ValueError: invalid literal for int() with base 10: '???'
2022-12-16 11:28:54,876 — ERROR : You entered a non-numeric value.
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/myfunctionlib.py", line 102, in menu_choice_get
    option = int(input(hint))
ValueError: invalid literal for int() with base 10: 'q'
2022-12-16 11:28:54,879 — ERROR : Please reenter a valid Number
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/myfunctionlib.py", line 102, in menu_choice_get
    option = int(input(hint))
ValueError: invalid literal for int() with base 10: 'q'
2022-12-16 11:28:55,220 — ERROR : You entered a non-numeric value.
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/myfunctionlib.py", line 102, in menu_choice_get
    option = int(input(hint))
ValueError: invalid literal for int() with base 10: 'q'
2022-12-16 11:28:55,221 — ERROR : Please reenter a valid Number
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/myfunctionlib.py", line 102, in menu_choice_get
    option = int(input(hint))
ValueError: invalid literal for int() with base 10: 'q'
2022-12-16 13:17:40,736 — ERROR : You entered a non-numeric value.
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/get.py", line 16, in int
    n = int(input(hint))
ValueError: invalid literal for int() with base 10: '???'
2022-12-16 13:17:40,738 — ERROR : Please reenter a valid value.
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/get.py", line 16, in int
    n = int(input(hint))
ValueError: invalid literal for int() with base 10: '???'
2022-12-16 18:06:00,359 — ERROR : 
Force Quit!
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/main.py", line 47, in <module>
    admin.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/admin.py", line 34, in sub_main
    manage_emergency_plan.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/manageEmergencyPlan.py", line 45, in sub_main
    back()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/myfunctionlib.py", line 132, in back
    key = input('Input "Q/q" to go back:')
KeyboardInterrupt
2022-12-16 18:07:24,945 — ERROR : 
Force Quit!
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/main.py", line 47, in <module>
    admin.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/admin.py", line 34, in sub_main
    manage_emergency_plan.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/manageEmergencyPlan.py", line 20, in sub_main
    match menu_choice_get(self.menu.count('\n') + 1, "\n-->"):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/myfunctionlib.py", line 102, in menu_choice_get
    option = int(input(hint))
KeyboardInterrupt
2022-12-16 18:07:59,557 — ERROR : 
Force Quit!
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/main.py", line 47, in <module>
    admin.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/admin.py", line 34, in sub_main
    manage_emergency_plan.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/manageEmergencyPlan.py", line 45, in sub_main
    back()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/myfunctionlib.py", line 132, in back
    key = input('Input "Q/q" to go back:')
KeyboardInterrupt
2022-12-16 18:09:16,936 — ERROR : 
Force Quit!
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/main.py", line 47, in <module>
    admin.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/admin.py", line 34, in sub_main
    manage_emergency_plan.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/manageEmergencyPlan.py", line 45, in sub_main
    back()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/myfunctionlib.py", line 132, in back
    key = input('Input "Q/q" to go back:')
KeyboardInterrupt
2022-12-16 18:10:31,813 — ERROR : 
Force Quit!
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/main.py", line 47, in <module>
    admin.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/admin.py", line 34, in sub_main
    manage_emergency_plan.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/manageEmergencyPlan.py", line 20, in sub_main
    match menu_choice_get(self.menu.count('\n') + 1, "\n-->"):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/myfunctionlib.py", line 102, in menu_choice_get
    option = int(input(hint))
KeyboardInterrupt
2022-12-16 18:10:33,412 — ERROR : 
Force Quit!
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/main.py", line 43, in <module>
    match menu_choice_get(menu('Login').count('\n') + 1, "\n-->"):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/myfunctionlib.py", line 102, in menu_choice_get
    option = int(input(hint))
KeyboardInterrupt
2022-12-16 18:10:41,847 — ERROR : 
Force Quit!
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/main.py", line 43, in <module>
    match menu_choice_get(menu('Login').count('\n') + 1, "\n-->"):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/myfunctionlib.py", line 102, in menu_choice_get
    option = int(input(hint))
KeyboardInterrupt
2022-12-16 18:10:57,979 — ERROR : 
Force Quit!
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/main.py", line 43, in <module>
    match menu_choice_get(menu('Login').count('\n') + 1, "\n-->"):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/myfunctionlib.py", line 102, in menu_choice_get
    option = int(input(hint))
KeyboardInterrupt
2022-12-16 18:11:05,699 — ERROR : You entered a non-numeric value.
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/myfunctionlib.py", line 102, in menu_choice_get
    option = int(input(hint))
ValueError: invalid literal for int() with base 10: 'dfgsfgd'
2022-12-16 18:11:05,701 — ERROR : Please reenter a valid Number
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/myfunctionlib.py", line 102, in menu_choice_get
    option = int(input(hint))
ValueError: invalid literal for int() with base 10: 'dfgsfgd'
2022-12-16 18:15:15,902 — ERROR : 
Force Quit!
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/main.py", line 43, in <module>
    match menu_choice_get(menu('Login').count('\n') + 1, "\n-->"):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/myfunctionlib.py", line 102, in menu_choice_get
    option = int(input(hint))
KeyboardInterrupt
2022-12-16 18:15:26,243 — ERROR : 
Force Quit!
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/main.py", line 47, in <module>
    admin.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/admin.py", line 34, in sub_main
    manage_emergency_plan.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/manageEmergencyPlan.py", line 45, in sub_main
    back()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/myfunctionlib.py", line 132, in back
    key = input('Input "Q/q" to go back:')
KeyboardInterrupt
2022-12-16 18:19:08,536 — ERROR : 
Force Quit!
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/main.py", line 53, in <module>
    volunteer.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/volunteer.py", line 47, in sub_main
    self.manage_personal_information()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/volunteer.py", line 66, in manage_personal_information
    self.edit_my_information()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/volunteer.py", line 85, in edit_my_information
    self.edit_campid()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/volunteer.py", line 263, in edit_campid
    new_campid = AccountCreation.get_camp_id()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/accountInput.py", line 26, in get_camp_id
    campID = Get.int(u"\U0001F539"+'Enter the camp ID:')
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/get.py", line 16, in int
    n = int(input(hint))
KeyboardInterrupt
2022-12-16 18:19:15,370 — ERROR : 
Force Quit!
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/main.py", line 45, in <module>
    utilities.admin_login()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/utilities.py", line 11, in admin_login
    password = input(u"\U0001F539" + "Input the password of admin:")
KeyboardInterrupt
2022-12-16 18:24:46,431 — ERROR : 
Force Quit!
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/main.py", line 47, in <module>
    admin.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/admin.py", line 34, in sub_main
    manage_emergency_plan.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/manageEmergencyPlan.py", line 45, in sub_main
    back()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/myfunctionlib.py", line 132, in back
    key = input('Input "Q/q" to go back:')
KeyboardInterrupt
2022-12-16 18:27:53,874 — ERROR : 
Force Quit!
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/main.py", line 47, in <module>
    admin.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/admin.py", line 34, in sub_main
    manage_emergency_plan.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/manageEmergencyPlan.py", line 45, in sub_main
    back()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/myfunctionlib.py", line 132, in back
    key = input('Input "Q/q" to go back:')
KeyboardInterrupt
2022-12-16 18:32:11,910 — ERROR : 
Force Quit!
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/main.py", line 49, in <module>
    v_ID = utilities.volunteer_login()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/utilities.py", line 26, in volunteer_login
    name = input(u"\U0001F539" + "Input your username:")
KeyboardInterrupt
2022-12-16 18:33:19,855 — ERROR : 
Force Quit!
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/main.py", line 47, in <module>
    admin.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/admin.py", line 34, in sub_main
    manage_emergency_plan.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/manageEmergencyPlan.py", line 45, in sub_main
    back()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/myfunctionlib.py", line 132, in back
    key = input('Input "Q/q" to go back:')
KeyboardInterrupt
2022-12-16 18:37:45,913 — ERROR : 
Force Quit!
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/main.py", line 47, in <module>
    admin.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/admin.py", line 34, in sub_main
    manage_emergency_plan.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/manageEmergencyPlan.py", line 45, in sub_main
    back()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/myfunctionlib.py", line 132, in back
    key = input('Input "Q/q" to go back:')
KeyboardInterrupt
2022-12-16 18:38:43,344 — ERROR : 
Force Quit!
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/main.py", line 47, in <module>
    admin.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/admin.py", line 34, in sub_main
    manage_emergency_plan.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/manageEmergencyPlan.py", line 45, in sub_main
    back()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/myfunctionlib.py", line 132, in back
    key = input('Input "Q/q" to go back:')
KeyboardInterrupt
2022-12-16 18:44:22,270 — ERROR : 
Force Quit!
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/main.py", line 47, in <module>
    admin.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/admin.py", line 34, in sub_main
    manage_emergency_plan.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/manageEmergencyPlan.py", line 45, in sub_main
    back()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/myfunctionlib.py", line 132, in back
    key = input('Input "Q/q" to go back:')
KeyboardInterrupt
2022-12-16 18:46:59,592 — ERROR : 
Force Quit!
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/main.py", line 47, in <module>
    admin.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/admin.py", line 34, in sub_main
    manage_emergency_plan.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/manageEmergencyPlan.py", line 45, in sub_main
    back()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/myfunctionlib.py", line 132, in back
    key = input('Input "Q/q" to go back:')
KeyboardInterrupt
2022-12-16 18:49:27,238 — ERROR : 
Force Quit!
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/main.py", line 47, in <module>
    admin.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/admin.py", line 34, in sub_main
    manage_emergency_plan.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/manageEmergencyPlan.py", line 45, in sub_main
    back()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/myfunctionlib.py", line 132, in back
    key = input('Input "Q/q" to go back:')
KeyboardInterrupt
2022-12-16 18:51:08,853 — ERROR : 
Force Quit!
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/main.py", line 47, in <module>
    admin.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/admin.py", line 34, in sub_main
    manage_emergency_plan.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/manageEmergencyPlan.py", line 45, in sub_main
    back()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/myfunctionlib.py", line 132, in back
    key = input('Input "Q/q" to go back:')
KeyboardInterrupt
2022-12-16 18:51:31,165 — ERROR : 
Force Quit!
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/main.py", line 47, in <module>
    admin.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/admin.py", line 34, in sub_main
    manage_emergency_plan.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/manageEmergencyPlan.py", line 45, in sub_main
    back()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/myfunctionlib.py", line 132, in back
    key = input('Input "Q/q" to go back:')
KeyboardInterrupt
2022-12-16 18:51:56,547 — ERROR : 
Force Quit!
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/main.py", line 47, in <module>
    admin.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/admin.py", line 34, in sub_main
    manage_emergency_plan.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/manageEmergencyPlan.py", line 45, in sub_main
    back()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/myfunctionlib.py", line 132, in back
    key = input('Input "Q/q" to go back:')
KeyboardInterrupt
2022-12-16 18:52:53,001 — ERROR : 
Force Quit!
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/main.py", line 47, in <module>
    admin.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/admin.py", line 34, in sub_main
    manage_emergency_plan.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/manageEmergencyPlan.py", line 45, in sub_main
    back()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/myfunctionlib.py", line 132, in back
    key = input('Input "Q/q" to go back:')
KeyboardInterrupt
2022-12-16 18:54:31,349 — ERROR : 
Force Quit!
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/main.py", line 49, in <module>
    v_ID = utilities.volunteer_login()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/utilities.py", line 26, in volunteer_login
    name = input(u"\U0001F539" + "Input your username:")
KeyboardInterrupt
2022-12-16 18:57:17,783 — ERROR : 
Force Quit!
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/main.py", line 47, in <module>
    admin.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/admin.py", line 34, in sub_main
    manage_emergency_plan.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/manageEmergencyPlan.py", line 58, in sub_main
    delete = emergency_plan.Delete_Emergency_Plan()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/emergency_plan_sql.py", line 174, in __init__
    self.delete_now()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/emergency_plan_sql.py", line 491, in delete_now
    self.row = input('Please choose which row '
KeyboardInterrupt
2022-12-16 18:59:02,971 — ERROR : 
Force Quit!
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/main.py", line 47, in <module>
    admin.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/admin.py", line 34, in sub_main
    manage_emergency_plan.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/manageEmergencyPlan.py", line 20, in sub_main
    match menu_choice_get(self.menu.count('\n') + 1, "\n-->"):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/myfunctionlib.py", line 102, in menu_choice_get
    option = int(input(hint))
KeyboardInterrupt
2022-12-16 19:02:23,188 — ERROR : You entered a non-numeric value.
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/myfunctionlib.py", line 102, in menu_choice_get
    option = int(input(hint))
ValueError: invalid literal for int() with base 10: ''
2022-12-16 19:02:23,191 — ERROR : Please reenter a valid Number
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/myfunctionlib.py", line 102, in menu_choice_get
    option = int(input(hint))
ValueError: invalid literal for int() with base 10: ''
2022-12-16 19:03:52,739 — ERROR : 
Force Quit!
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/main.py", line 43, in <module>
    match menu_choice_get(menu('Login').count('\n') + 1, "\n-->"):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/myfunctionlib.py", line 102, in menu_choice_get
    option = int(input(hint))
KeyboardInterrupt
2022-12-16 19:23:01,337 — ERROR : 
Force Quit!
Traceback (most recent call last):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/main.py", line 47, in <module>
    admin.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/admin.py", line 34, in sub_main
    manage_emergency_plan.sub_main()
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/manageEmergencyPlan.py", line 20, in sub_main
    match menu_choice_get(self.menu.count('\n') + 1, "\n-->"):
  File "/Users/junfeng/Documents/WorkSpace/Python/IntroProgramming/emergency-system/myfunctionlib.py", line 102, in menu_choice_get
    option = int(input(hint))
KeyboardInterrupt
