2022-12-05 23:20:55,351 — ERROR : unable to open database file
Traceback (most recent call last):
  File "/home/lingpeng/emergency_plan/emergency-system/core_code/db_connect_ref.py", line 15, in connect_db
    conn = sqlite3.connect("info_files/emergency_system.db", timeout=1000.0 )
sqlite3.OperationalError: unable to open database file
2022-12-05 23:57:47,203 — ERROR : Please input the day between 1 and 31
Traceback (most recent call last):
  File "/home/lingpeng/emergency_plan/emergency-system/core_code/refugee_validation.py", line 50, in date_format_check
    raise exc.day_out_of_range
refugee_exception.day_out_of_range
2022-12-05 23:57:52,328 — ERROR : Please input the birthdate in YYYY-MM-DD format e.g. 2022-11-20
Traceback (most recent call last):
  File "/home/lingpeng/emergency_plan/emergency-system/core_code/refugee_validation.py", line 48, in date_format_check
    raise exc.wrong_birthdate_format
refugee_exception.wrong_birthdate_format
2022-12-05 23:58:42,226 — ERROR : Your input is invalid. Please enter either 'Yes' or 'No'
Traceback (most recent call last):
  File "/home/lingpeng/emergency_plan/emergency-system/core_code/refugee_validation.py", line 203, in yn_valid
    raise exc.wrong_yn_input
refugee_exception.wrong_yn_input
2022-12-05 23:58:44,623 — ERROR : Your input is invalid. Please enter either 'Yes' or 'No'
Traceback (most recent call last):
  File "/home/lingpeng/emergency_plan/emergency-system/core_code/refugee_validation.py", line 203, in yn_valid
    raise exc.wrong_yn_input
refugee_exception.wrong_yn_input
2022-12-05 23:58:58,690 — ERROR : Your input is invalid. Please enter either 'Yes' or 'No'
Traceback (most recent call last):
  File "/home/lingpeng/emergency_plan/emergency-system/core_code/refugee_validation.py", line 203, in yn_valid
    raise exc.wrong_yn_input
refugee_exception.wrong_yn_input
2022-12-05 23:59:17,422 — ERROR : Please input the birthdate in YYYY-MM-DD format e.g. 2022-11-20
Traceback (most recent call last):
  File "/home/lingpeng/emergency_plan/emergency-system/core_code/refugee_validation.py", line 48, in date_format_check
    raise exc.wrong_birthdate_format
refugee_exception.wrong_birthdate_format
2022-12-06 00:29:18,394 — ERROR : Please enter a numerical value for your input.
Traceback (most recent call last):
  File "/home/lingpeng/emergency_plan/emergency-system/core_code/refugee_validation.py", line 136, in refugee_validity_check_by_ID
    ref_id = int(input(f"Please input refugee ID of whom you wish to {cond} the information: "))
ValueError: invalid literal for int() with base 10: 'dqw'
2022-12-06 00:29:27,006 — ERROR : Your input is invalid in our database
Traceback (most recent call last):
  File "/home/lingpeng/emergency_plan/emergency-system/core_code/refugee_validation.py", line 132, in refugee_validity_check_by_ID
    raise exc.refugee_id_out_of_range
refugee_exception.refugee_id_out_of_range
